# Generated by Django 3.1.2 on 2020-12-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resource_Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='requirement',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resource',
            name='note',
            field=models.TextField(max_length=1000),
        ),
    ]
