# Generated by Django 3.1 on 2020-11-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='event_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
