# Generated by Django 3.1 on 2020-11-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='csvfile',
            field=models.FileField(default=0, upload_to='csvfile_for_guest/<built-in function id>/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='rules',
            field=models.TextField(default=''),
        ),
    ]
