# Generated by Django 3.1 on 2020-11-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_auto_20201112_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule1', models.TextField(default='')),
                ('rule2', models.TextField(default='')),
                ('rule3', models.TextField(default='')),
                ('rule4', models.TextField(default='')),
                ('rule5', models.TextField(default='')),
            ],
        ),
    ]
