# Generated by Django 3.1.2 on 2020-10-12 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_auto_20201012_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created',
        ),
    ]
