# Generated by Django 3.1 on 2020-11-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_rule_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='event_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
