# Generated by Django 3.1 on 2020-11-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_auto_20201114_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rule4',
            field=models.TextField(blank=True, default=''),
        ),
    ]
