# Generated by Django 3.1 on 2020-11-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='event_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
