# Generated by Django 3.1 on 2020-11-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_auto_20201114_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rule1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule5',
            field=models.TextField(blank=True, default=''),
        ),
    ]
