# Generated by Django 3.1.2 on 2020-11-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_auto_20201113_1242'),
        ('Events', '0004_rule_event_id'),
    ]

    operations = [
    ]
