# Generated by Django 3.1.2 on 2020-11-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_merge_20201113_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='csvfile',
        ),
        migrations.RemoveField(
            model_name='event',
            name='rules',
        ),
        migrations.AddField(
            model_name='event',
            name='contact',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
