# Generated by Django 3.1.2 on 2020-11-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('event_name', models.CharField(max_length=50)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_phone', models.CharField(max_length=12)),
                ('contact_email', models.EmailField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default='')),
                ('timestamp_for_finish', models.DateTimeField(default='')),
                ('organiser', models.CharField(max_length=100)),
                ('about', models.TextField(default='')),
                ('contact', models.TextField(default='')),
                ('details', models.TextField(default='')),
                ('link', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'events',
            },
        ),
        migrations.CreateModel(
            name='guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_for_event', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('motto', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('event_name', models.CharField(max_length=100)),
                ('first_prize', models.CharField(max_length=100)),
                ('second_prize', models.CharField(blank=True, default='', max_length=100)),
                ('third_prize', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('event_name', models.CharField(default='', max_length=50)),
                ('rule1', models.TextField(default='')),
                ('rule2', models.TextField(blank=True, default='')),
                ('rule3', models.TextField(blank=True, default='')),
                ('rule4', models.TextField(blank=True, default='')),
                ('rule5', models.TextField(blank=True, default='')),
            ],
        ),
    ]
