# Generated by Django 3.1.2 on 2020-11-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='details',
        ),
    ]
