# Generated by Django 3.1.2 on 2020-12-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailtext',
            name='attachment',
        ),
        migrations.AddField(
            model_name='mailtext',
            name='event_id',
            field=models.IntegerField(default='-1'),
        ),
    ]
