# Generated by Django 3.1.2 on 2020-12-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20201201_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailtext',
            options={'verbose_name': 'Email to send', 'verbose_name_plural': 'Emails to send'},
        ),
    ]
