# Generated by Django 3.1.2 on 2020-12-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_auto_20201201_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtext',
            name='message',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mailtext',
            name='subject',
            field=models.TextField(max_length=500),
        ),
    ]
