# Generated by Django 3.1.2 on 2020-11-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='customer_name',
            new_name='Name',
        ),
        migrations.AddField(
            model_name='feedback',
            name='event_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
