# Generated by Django 3.1 on 2020-11-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0002_auto_20201115_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdata',
            name='point',
            field=models.IntegerField(default='0'),
        ),
    ]
